spring.application.name=backend-core

# 1. Dónde está la base de datos (URL) - AQUI ESTABA EL CAMBIO NECESARIO
spring.datasource.url=jdbc:mysql://localhost:3306/recommendations_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

# 2. Quién entra (Usuario)
spring.datasource.username=root

# 3. La contraseña (Tu clave 'admin')
spring.datasource.password=admin

# 4. Configuración para que Java cree las tablas solo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect